apiVersion: v1
kind: Pod
metadata:
  name: ndnperf-client
  namespace: ndn
spec:
  containers:
  - name: ndnperf-client
    image: otaviocruz/ndnperf-client:2.0
    command: ["/bin/sleep", "365d"]
    resources:
      limits:
        memory: "250M"
        cpu: "500m"
    
  #nodeName: otaviopc1-270e5j-2570ej

