apiVersion: v1
kind: Pod
metadata:
  name: ndnperf-server
  namespace: ndn
spec:
  containers:
  - name: ndnperf-server
    image: otaviocruz/ndnperf-server:1.0
    command: ["/bin/sleep", "365d"]
    resources:
      limits:
        memory: "150M"
        cpu: "300m"
  nodeName: otaviopc2-270e5j-2570ej
